#!/usr/bin/env bash
set -eo pipefail

# List tags and counts in bookmarks file.
#
# Usage:
# ./tags [file]
#
# Examples:
# 1. list tags (defaults to bookmarks.txt)
# ./tags
#
# 2. list tags in a different file
# ./tags archive.txt
#
# 3. filter and list tags
# ./q '/:tags.*\bbook\b/' | ./tags

file="${2:-bookmarks.txt}"

if [ -t 0 ]; then
    exec < "$file"
fi

awk '/^:tags / {$1=""; print}' | xargs -n1 | sort | uniq -c | sort -rn
