#!/usr/bin/env bash
set -eo pipefail

# List tags and counts in bookmarks file.
#
# Usage:
# ./tags [file]
#
# Examples:
# 1. list tags (defaults to bookmarks.txt)
# ./tags
#
# 2. list tags in a different file
# ./tags archive.txt
#
# 3. filter and list tags
# ./q '/:tags.*\bbook\b/' | ./tags

if [[ -n "$1" && -f "$1" ]]; then
    input_file="$1"
elif [[ ! -t 0 ]]; then
    input_file="/dev/stdin"
else
    input_file="bookmarks.txt"
fi

awk '/^:tags / {$1=""; print}' "$input_file" | xargs -n1 | sort | uniq -c | sort -rn
